### ISSUE TITLE
您好，请问fcdata-zh-luban和fcdata-zh-codefuse的区别是啥？

### ISSUE THREAD

**Issue by GeniusYx** [codefuse-ai/codefuse-devops-eval#16]
您好，打扰了，请问两个评测集的区别是啥啊？两份测试集report的结果分数差异很大？

**Comment by lightislost** [comment]
fcdata-zh-luban 是经过self-instruct和llm标注筛选得到的；fcdata-zh-codefuse是由人工编写标注完成的
