### ISSUE TITLE
数据集需要进一步清洗

### ISSUE THREAD

**Issue by hhk123** [codefuse-ai/codefuse-devops-eval#2]
机器学习
<img width="1369" alt="机器学习错误" src="https://github.com/codefuse-ai/codefuse-devops-eval/assets/34189310/122ddb50-1d9f-4b7f-beb9-0f663aae3728">

**Comment by PanameraXXX** [comment]
针对“机器学习”这份数据我们已经做了清洗，另外我们还计划了在12月进行一次全样本的人工核对。感谢～
