### ISSUE TITLE
支持多种开源模型prompt格式

### ISSUE THREAD

**Issue by donttal** [codefuse-ai/codefuse-devops-eval#3]
# 测试文档优化

是不是可以提供多种模型的prompt模版以便更好降低偏差
<img width="1005" alt="image" src="https://github.com/codefuse-ai/codefuse-devops-eval/assets/30567352/40b97266-7037-4ad6-a7a2-bcb2d9c5596a">

**Comment by PanameraXXX** [comment]
当前是支持千问、百川、Internlm等大模型格式的，后续会开放出来～有特殊想要支持的模型也可以跟我们沟通，感谢～
